AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Task API

Resources:
  CreateTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/create-task/
      Handler: app.lambda_handler
      Runtime: python3.12
      MemorySize: 128
      Timeout: 10
      Events:
        CreateTaskApi:
          Type: Api
          Properties:
            Path: /tasks
            Method: post
